# This file was generated by GoReleaser. DO NOT EDIT.
cask "kupe" do
  version "1.6.1"

  on_macos do
    on_intel do
      url "https://github.com/kupecloud/kupe-cli/releases/download/v#{version}/kupe_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/kupecloud/kupe-cli/releases/download"
      sha256 "0d122dffad965972291b446295f54c0f6061e8bd6765b1389335c8b64546ccfa"
    end
    on_arm do
      url "https://github.com/kupecloud/kupe-cli/releases/download/v#{version}/kupe_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/kupecloud/kupe-cli/releases/download"
      sha256 "e084ae56ba022eb83644934ce9d70fbc169783e582623c34a2a99610bd567321"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kupecloud/kupe-cli/releases/download/v#{version}/kupe_#{version}_linux_amd64.tar.gz",
        verified: "github.com/kupecloud/kupe-cli/releases/download"
      sha256 "f271684ac952c9a0c9b7342338314a41fd188223ad310d9515e0a7b5207327d5"
    end
    on_arm do
      url "https://github.com/kupecloud/kupe-cli/releases/download/v#{version}/kupe_#{version}_linux_arm64.tar.gz",
        verified: "github.com/kupecloud/kupe-cli/releases/download"
      sha256 "a10679a89e1b23d753744c334409d287c815c090bdd734dd93732a125eee6adb"
    end
  end

  name "kupe"
  desc "Official CLI for Kupe Cloud"
  homepage "https://kupe.cloud/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kupe"
  manpage "manpages/kupe.1.gz"
  bash_completion "completions/kupe.bash"
  fish_completion "completions/kupe.fish"
  zsh_completion "completions/kupe.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kupe"]
    end
  end

  # No zap stanza required

end
