# This file was generated by GoReleaser. DO NOT EDIT.
cask "kupe" do
  version "1.8.12"

  on_macos do
    on_intel do
      url "https://github.com/kupecloud/kupe-cli/releases/download/v#{version}/kupe_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/kupecloud/kupe-cli/releases/download"
      sha256 "03925716e53efea605185a7da674a9c022f0965b1e85729972e38039f4ded6e9"
    end
    on_arm do
      url "https://github.com/kupecloud/kupe-cli/releases/download/v#{version}/kupe_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/kupecloud/kupe-cli/releases/download"
      sha256 "f7fd576bb166eec879f3b83754cff1934384ab02f2a93f9a34b76ccb11d594a1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kupecloud/kupe-cli/releases/download/v#{version}/kupe_#{version}_linux_amd64.tar.gz",
        verified: "github.com/kupecloud/kupe-cli/releases/download"
      sha256 "44d5ac57a29e5773a5c9172869a37a66a2c8ef69d430c789e180e29bf888918b"
    end
    on_arm do
      url "https://github.com/kupecloud/kupe-cli/releases/download/v#{version}/kupe_#{version}_linux_arm64.tar.gz",
        verified: "github.com/kupecloud/kupe-cli/releases/download"
      sha256 "3b3fe0cc18f484375f7e29fa4537ca4dbc8a50311bb332655474b9a08a100b84"
    end
  end

  name "kupe"
  desc "Official CLI for Kupe Cloud"
  homepage "https://kupe.cloud/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kupe"
  manpage "manpages/kupe.1.gz"
  bash_completion "completions/kupe.bash"
  fish_completion "completions/kupe.fish"
  zsh_completion "completions/kupe.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kupe"]
    end
  end

  zap trash: [
      "~/.config/kupe",
    ]

end
