# This file was generated by GoReleaser. DO NOT EDIT.
cask "kupe" do
  version "1.6.0"

  on_macos do
    on_intel do
      url "https://github.com/kupecloud/kupe-cli/releases/download/v#{version}/kupe_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/kupecloud/kupe-cli/releases/download"
      sha256 "735b620aa5c7539406102b82075ea285accfb794fa4564001d8ee8b64b21d05e"
    end
    on_arm do
      url "https://github.com/kupecloud/kupe-cli/releases/download/v#{version}/kupe_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/kupecloud/kupe-cli/releases/download"
      sha256 "e299701b4b424b0a2896b614032795fc7f8a0bf6fa04754556271fb0ce226e51"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kupecloud/kupe-cli/releases/download/v#{version}/kupe_#{version}_linux_amd64.tar.gz",
        verified: "github.com/kupecloud/kupe-cli/releases/download"
      sha256 "6862b6f4d8960b2822b7202b9c5c0b9c171ba8471294f9cad2e59bd335c657f4"
    end
    on_arm do
      url "https://github.com/kupecloud/kupe-cli/releases/download/v#{version}/kupe_#{version}_linux_arm64.tar.gz",
        verified: "github.com/kupecloud/kupe-cli/releases/download"
      sha256 "63809aafd32be164c961c2797c11a3e3c89f8869428e412aa99a772df1e8e6ec"
    end
  end

  name "kupe"
  desc "Official CLI for Kupe Cloud"
  homepage "https://kupe.cloud/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kupe"
  manpage "manpages/kupe.1.gz"
  bash_completion "completions/kupe.bash"
  fish_completion "completions/kupe.fish"
  zsh_completion "completions/kupe.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kupe"]
    end
  end

  # No zap stanza required

end
